export const projects = [
  {
    title: 'Todo api',
    description: 'A RESTful API for managing todo\'s using all CRUD common operations.',
    stack: ['JavaScript', 'Typescript', 'NodeJS', 'Express', 'MongoDB', 'Jest'],
    image: 'https://via.placeholder.com/250x300',
    repo: 'https://github.com/nip10/todo-api',
    demo: '',
  },
  {
    title: 'Todo\'s Manager',
    description: 'Front-end for managing todo\'s.',
    stack: ['HTML5', 'CSS3', 'Typescript', 'React'],
    image: 'https://via.placeholder.com/250x300',
    repo: 'https://github.com/nip10/todo-react-ts',
    demo: '',
  },
  {
    title: 'Chat',
    description: 'Simple chat webapp.',
    stack: ['HTML5', 'CSS3', 'JavaScript', 'NodeJS', 'Express', 'SocketIO'],
    image: 'https://via.placeholder.com/250x300',
    repo: 'https://github.com/nip10/node-chat-app',
    demo: '',
  },
  {
    title: 'TSM - TvShow Manager',
    description: 'Manage your favourite tvshows and discover new ones. Relies on the TheTVDB API to get tvshow\'s information.',
    stack: ['HTML5', 'CSS3', 'JavaScript', 'NodeJS', 'PostgreSQL', 'Express', 'SocketIO'],
    image: 'https://via.placeholder.com/250x300',
    repo: 'https://github.com/nip10/tvshows-manager',
    demo: '',
  },
  {
    title: 'Telegram Bot',
    description: 'A Telegram bot that provides weather information. Location can be manually inputted or using the device\'s location. Users can add locations as favourites for a better experience.',
    stack: ['Javascript', 'Express', 'NodeJS'],
    image: 'https://via.placeholder.com/250x300',
    repo: 'https://github.com/nip10/telegram-bot',
    demo: '',
  },
];